### PR TITLE
Add 'magento-core-package-name' option

### PR DESCRIPTION
**Pull request by danelowe**
Add an option called 'magento-core-package-name'. If this is present, it will be used to identify the Magento core package rather than the package type.

e.g. OpenMage/magento-lts has a package type of 'magento-source' rather than 'magento-core'

### CODE REVIEW

**Comment by AydinHassan** [comment]
Hey thanks! I will check this out hopefully second half of this coming week, currently moving house 😄

**Comment by AydinHassan** [comment]
@danelowe Looking at this I would prefer we just modify the type to be an array and add in `magento-source`. I don't really think it needs to be configurable, what do you think?

**Comment by danelowe** [comment]
@AydinHassan That would work in my case. I just don't know what other package types people have used on other Magento repositories, so figured it would be best to add a config option and not change the default behaviour.

**Comment by AydinHassan** [comment]
@danelowe I think we should be a bit more explicit at first, if it becomes a problem again, we can re-visit. Do you like to update the PR, or I can do it when I get some free time?

**Comment by danelowe** [comment]
I'll update it when I get a chance. Might be a couple of days.

**Comment by djallits** [comment]
This is a great enhancement... Now I can maintain magento/community and magento/enterprise repos.

**Comment by AydinHassan** [comment]
@djallits You could always do that, we do that here. We have two repos, both with type `magento-core` and then package name are `magento/ce` and `magento/ee`. But if this helps you then great :smile: .

**Comment by midlan** [comment]
I am trying to use this feature. In the [release 1.4.0](https://github.com/AydinHassan/magento-core-composer-installer/releases/tag/1.4.0) is mentioned `magento-core-package-type`. In the source seems that `magento-core-package-name` is right. Can someone provide proper doc in README?

**Comment by AydinHassan** [comment]
@midlan they are different things. Use one or the other.

**Comment by midlan** [comment]
OK got it now. But documentation is missing for both.

**Comment by AydinHassan** [comment]
@midlan feel free to PR. I am not working with Magento anymore.

**Pull request merged**
