### PR TITLE
Composer 2.0 compatibility added

### PR DESCRIPTION
**Pull request by astyczen**

### CODE REVIEW

**Comment by AydinHassan** [comment]
Hi @astyczen I'm not sure why the travis tests are not reporting on the PR but they did not run correctly: https://travis-ci.org/github/AydinHassan/magento-core-composer-installer/builds/741443389

**Comment by astyczen** [comment]
Hi @AydinHassan, weird as it showed all on green. I will change that to composer update than. Will the composer.lock update automatically in the repo as I saw it was in the .gitignore?

**Comment by AydinHassan** [comment]
@astyczen that could be why it's not working, try removing the lock file from the .gitignore please :)

**Comment by AydinHassan** [comment]
Thanks @astyczen - if you can use the dev-master branch to test that everything still works, eg the core is deployed correctly in one of your projects, i'll tag a release.

**Comment by AydinHassan** [comment]
Don't worry about scrutiniser, I've disabled it now

**Comment by astyczen** [comment]
@AydinHassan will test this in a sec, thanks!

**Pull request merged**
