### PR TITLE
git ignore

### PR DESCRIPTION
**Pull request by luckyraul**

### CODE REVIEW

**Comment by luckyraul** [comment]
#22

**Comment by AydinHassan** [comment]
This doesn't work, it is valid for the gitignore to not exist on installing

**Comment by luckyraul** [comment]
It helped in my situation

**Comment by AydinHassan** [comment]
Yes but breaks for others, you can see the tests fail.

**Comment by luckyraul** [comment]
Yes. I see. I guess I should split somehow removing and installing.

**Pull request closed without merging**
